# This file was generated by GoReleaser. DO NOT EDIT.
cask "edilint" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "c932bf3f6e03c7b93c397ee9abf873b8a129b073264a1fe7411b7004f41e6493"
      url "https://github.com/crb2nu/edilint/releases/download/v#{version}/edilint_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b8b3cc658af7b19b4ccae85ab81e3d1d04ad249e8f4dc06c0fc88f46a67f874d"
      url "https://github.com/crb2nu/edilint/releases/download/v#{version}/edilint_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d896fc352d6dd5f6a4287f6fcaeb8596d4dcf035e1304bf8cd1dca402aab627f"
      url "https://github.com/crb2nu/edilint/releases/download/v#{version}/edilint_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a462aec00000669a44d5fec417cf03e5454af942d576dbc600944839a4b24db3"
      url "https://github.com/crb2nu/edilint/releases/download/v#{version}/edilint_#{version}_linux_amd64.tar.gz"
    end
  end

  name "edilint"
  desc "Pre-send linter for healthcare interchange files"
  homepage "https://github.com/crb2nu/edilint"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "edilint"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/edilint"]
    end
  end

  # No zap stanza required
end
